### ISSUE TITLE
it does not download

### ISSUE THREAD

**Issue by Ashrafty** [Hexer10/youtube_downloader_flutter#1]
it does not download on windows...and even if it does sometimes it hides the downloaded content...but other than that it's perfect you my great sir out done yourself i'll make sure to get you a cup of coffee

**Comment by Hexer10** [comment]
This is still a WIP project, I'm aware that sometimes there could be some issue, I'm actively working and them.

Thanks for you feedback!

**Comment by Hexer10** [comment]
Should be fixed in the latest versions, there was a bug in the youtube_explode_dart api, but now should be fixed
