### ISSUE TITLE
Why is ffmpeg not being used anywere if it's included.

### ISSUE THREAD

**Issue by prateekmedia** [Hexer10/youtube_downloader_flutter#13]
Hi, I got through the code and found out that ffmpeg isn't being used to mux video and audio tracks for videos that doesn't have any audio.

Also Video+Audio already have audio so ffmpeg is not needed there.

So can you tell me why you included that in this project then?

**Comment by Hexer10** [comment]
I'm sorry for the very late reply I just noticed this issue now.
You can that ffmpeg is used here:
https://github.com/Hexer10/youtube_downloader_flutter/blob/bed04f0c90e951f26d18944cedd663e00ee3e4dd/lib/src/models/download_manager.dart#L280-L406

Mobile and desktop have two different implementations.
You can test this feature by holding one stream and then another and you should be able to merge them.
